package com.example.pvpscheduler.tools;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import java.io.*;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.*;
import java.util.jar.*;

/**
 * Tool to generate stackmap frames for obfuscated JAR files
 * This fixes VerifyError: Expecting a stackmap frame
 */
public class StackMapFrameGenerator {

    public static void main(String[] args) {
        if (args.length != 1) {
            System.err.println("Usage: StackMapFrameGenerator <jar-file>");
            System.exit(1);
        }

        // Debug: Check if dependencies are available
        try {
            Class.forName("org.bukkit.plugin.java.JavaPlugin");
            System.out.println("Dependency Check: Bukkit API found.");
        } catch (ClassNotFoundException e) {
            System.err.println("Dependency Check: Bukkit API NOT found! StackMapFrameGenerator will likely fail.");
        }

        String jarPath = args[0];
        File jarFile = new File(jarPath);

        if (!jarFile.exists()) {
            System.err.println("JAR file not found: " + jarPath);
            System.exit(1);
        }

        try {
            System.out.println("Generating stackmap frames for: " + jarPath);
            generateStackMapFrames(jarFile);
            System.out.println("Successfully processed jar!");
        } catch (Exception e) {
            System.err.println("Error generating stackmap frames: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }

    private static void generateStackMapFrames(File jarFile) throws IOException {
        File tempFile = new File(jarFile.getAbsolutePath() + ".tmp");

        // Create a ClassLoader that includes the JAR file so ASM can find the classes
        URL[] urls = { jarFile.toURI().toURL() };
        URLClassLoader classLoader = new URLClassLoader(urls, Thread.currentThread().getContextClassLoader());

        try (JarInputStream jis = new JarInputStream(new FileInputStream(jarFile));
                JarOutputStream jos = new JarOutputStream(new FileOutputStream(tempFile))) {

            JarEntry entry;
            while ((entry = jis.getNextJarEntry()) != null) {
                String name = entry.getName();

                if (name.endsWith(".class")) {
                    // Check if this is the problematic class
                    if (name.contains("PvPScheduler")) {
                        System.out.println("Processing class: " + name);
                    }

                    // Read class file
                    ByteArrayOutputStream baos = new ByteArrayOutputStream();
                    byte[] buffer = new byte[8192];
                    int bytesRead;
                    while ((bytesRead = jis.read(buffer)) != -1) {
                        baos.write(buffer, 0, bytesRead);
                    }
                    byte[] classBytes = baos.toByteArray();

                    try {
                        // Generate stackmap frames using ASM with custom ClassWriter
                        ClassReader cr = new ClassReader(classBytes);

                        // Use correct flags: COMPUTE_FRAMES implies COMPUTE_MAXS
                        ClassWriter cw = new CustomClassWriter(cr, ClassWriter.COMPUTE_FRAMES, classLoader);

                        // Wrap the ClassWriter in a custom ClassVisitor to inspect calls
                        ClassVisitor cv = new InspectingClassVisitor(cw);

                        // EXPAND_FRAMES is good, but maybe SKIPPING existing frames helps force
                        // recomputation?
                        cr.accept(cv, ClassReader.EXPAND_FRAMES);

                        byte[] newClassBytes = cw.toByteArray();

                        // Check for StackMapTable string presence as heuristic
                        if (name.contains("PvPScheduler")) {
                            String content = new String(newClassBytes, java.nio.charset.StandardCharsets.ISO_8859_1);
                            if (!content.contains("StackMapTable")) {
                                System.err.println(
                                        "WARNING: StackMapTable attribute NOT found in generated bytes for " + name);
                            } else {
                                System.out
                                        .println("INFO: StackMapTable attribute FOUND in generated bytes for " + name);
                            }
                            System.out.println(
                                    "Original size: " + classBytes.length + ", New size: " + newClassBytes.length);
                        }

                        // Write to output JAR
                        JarEntry newEntry = new JarEntry(name);
                        newEntry.setSize(newClassBytes.length);
                        jos.putNextEntry(newEntry);
                        jos.write(newClassBytes);
                        jos.closeEntry();

                        if (name.contains("PvPScheduler")) {
                            System.out.println("Finished processing: " + name);
                        }
                    } catch (Exception e) {
                        throw new RuntimeException("Failed to process " + name + ": " + e.getMessage(), e);
                    }
                } else {
                    // Copy non-class files as-is
                    JarEntry newEntry = new JarEntry(name);
                    jos.putNextEntry(newEntry);
                    byte[] buffer = new byte[8192];
                    int bytesRead;
                    while ((bytesRead = jis.read(buffer)) != -1) {
                        jos.write(buffer, 0, bytesRead);
                    }
                    jos.closeEntry();
                }
            }
        }

        // Replace original file with new file
        Files.move(tempFile.toPath(), jarFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
    }

    // Inspect calls to ClassWriter
    private static class InspectingClassVisitor extends ClassVisitor {
        public InspectingClassVisitor(ClassVisitor cv) {
            super(Opcodes.ASM9, cv);
        }

        @Override
        public void visit(int version, int access, String name, String signature, String superName,
                String[] interfaces) {
            // Keep existing logic, version is passed through
            super.visit(version, access, name, signature, superName, interfaces);
        }

        @Override
        public MethodVisitor visitMethod(int access, String name, String descriptor, String signature,
                String[] exceptions) {
            // Check cancelTask
            if (name.equals("cancelTask") || name.equals("cancelTask_impl") || name.equals("lambda$spin$0")) { // Not
                                                                                                               // sure
                                                                                                               // exact
                                                                                                               // method
                                                                                                               // name
                                                                                                               // after
                                                                                                               // obfuscation?
                                                                                                               // No,
                                                                                                               // keep
                                                                                                               // logic.
                // Just to ensure visitMethod called.
            }
            return new InspectingMethodVisitor(super.visitMethod(access, name, descriptor, signature, exceptions));
        }
    }

    private static class InspectingMethodVisitor extends MethodVisitor {
        public InspectingMethodVisitor(MethodVisitor mv) {
            super(Opcodes.ASM9, mv);
        }
        // Could intercept calls here
    }

    private static class CustomClassWriter extends ClassWriter {
        private final ClassLoader classLoader;

        public CustomClassWriter(ClassReader classReader, int flags, ClassLoader classLoader) {
            super(classReader, flags);
            this.classLoader = classLoader;
        }

        @Override
        protected String getCommonSuperClass(String type1, String type2) {
            // System.out.println("INFO: getCommonSuperClass called for " + type1 + " and "
            // + type2); // Verbose!

            Class<?> c, d;
            try {
                c = Class.forName(type1.replace('/', '.'), false, classLoader);
                d = Class.forName(type2.replace('/', '.'), false, classLoader);
            } catch (Exception e) {
                System.err.println("ERROR: getCommonSuperClass failed to load: " + e.getMessage());
                throw new RuntimeException("Class not found: " + e.toString());
            }
            if (c.isAssignableFrom(d)) {
                return type1;
            }
            if (d.isAssignableFrom(c)) {
                return type2;
            }
            if (c.isInterface() || d.isInterface()) {
                return "java/lang/Object";
            } else {
                do {
                    c = c.getSuperclass();
                } while (!c.isAssignableFrom(d));
                return c.getName().replace('.', '/');
            }
        }
    }
}
